Fix(sidebar): update selected item bg color to match PF5
redhat-developer/red-hat-developer-hub-theme pull request #44
Opened 2024-09-25 22:10 UTC by ciiay

For [RHIDP-3139](https://issues.redhat.com/browse/RHIDP-3139)

Screen recording

https://github.com/user-attachments/assets/943ad69f-0656-489d-a8aa-d6523dc372eb

2024-09-26 05:40 UTC, ShiranHi commented
Awesome, thank you @ciiay

2024-09-27 12:22 UTC, jerolimov requested changes
Hi, this look in general fine, but could we keep it backward compatible?

We might need to update that also in the documentation.

Do you think you can do the yaml change there and let this review by someone from the docs team? @linfraze wrote the initial doc. (We do that for 1.4+ so there is no need to be worried here about any timeline, right?)

https://github.com/search?q=repo%3Aredhat-developer%2Fred-hat-developers-documentation-rhdh%20sideBarBackgroundColor&type=code

2024-09-27 12:22 UTC, jerolimov commented on src/themes/rhdh-1.2.0/componentOverrides.ts
> -          backgroundColor: themePalette.general.sideBarBackgroundColor,
Please keep 1.2.0 untouched. It's just for reference if we use the 0.3.x and new release of the theme and switch quickly between 1.2.0 theme and latest

2024-09-27 12:22 UTC, jerolimov commented on src/themes/rhdh-1.2.0/defaultThemePalette.ts
> -        sideBarBackgroundColor: "#1b1d21",
Same here. Please revert that change.

2024-09-27 12:22 UTC, jerolimov commented on src/themes/rhdh-1.2.0/defaultThemePalette.ts
> -      sideBarBackgroundColor: "#212427",
Same here, please revert that change.

2024-09-27 12:22 UTC, jerolimov commented on src/themes/rhdh/components.ts
> +          backgroundColor: general.sidebarBackgroundColor,
I like that naming improvement, in general. But this might affect the compatibility, or was it never called `sideBarBackgroundColor` before?

Can we have maybe both types, and merge it here from both values? Prefer the new one, and take the old one as fallback?

```suggestion
          backgroundColor: general.sidebarBackgroundColor ?? general.sideBarBackgroundColor,
```

2024-09-27 12:22 UTC, jerolimov commented on src/types.ts
> +    sidebarBackgroundColor: string;
For my ask above, should we maybe mark this as deprecated instead?

```suggestion
    /** @deprecated please use `sidebarBackgroundColor` instead */
    sideBarBackgroundColor: string;
    sidebarBackgroundColor: string;
```

2024-09-27 19:45 UTC, jerolimov requested changes

2024-09-27 19:45 UTC, jerolimov commented on src/types.ts
>      sideBarBackgroundColor: string;
We can make it optional and remove the default value, or?

2024-09-27 19:45 UTC, jerolimov commented on src/themes/rhdh/lightTheme.ts
>          sideBarBackgroundColor: "#212427",
We can make it optional and remove the default value, or?

2024-09-27 21:01 UTC, jerolimov approved these changes
Diff looks good, but I would like to test it a bit before I push the merge button.

/lgtm
/approve

2024-09-30 08:29 UTC, jerolimov commented
Tested this with our RHDH app (backstage-showcase).

/label jira-valid/reference
/lgtm

2024-09-30 08:30 UTC, merged